inp_file: ctown_map.inp

plcs:
- name: PLC1
  sensors:
  - PU1F
  - PU2F
  - J280
  - J269
  actuators:
  - PU1
  - PU2
- name: PLC2
  sensors:
  - T1
  actuators:
  - V2
  - PU4
  - PU5
  - PU6
  - PU7
- name: PLC3
  sensors:
  - T2
  - V2F
  - J300
  - J256
  - J289
  - J415
  - J14
  - J422
  - PU4F
  - PU5F
  - PU6F
  - PU7F
- name: PLC4
  sensors:
  - T3
  - T4
  actuators:
  - PU8
  - PU10
  - PU11
- name: PLC5
  sensors:
  - PU8F
  - PU10F
  - PU11F
  - J302
  - J306
  - J307
  - J317
- name: PLC7
  sensors:
  - T5
- name: PLC8
  sensors:
  - T6
- name: PLC9
  sensors:
  - T7

network_topology_type: complex

iterations: 3

demand: pdd

log_level: debug

simulator: epynet

attacks:
  network_attacks:
  - name: plc4attack
    type: server_mitm
    trigger:
      type: time  
      start: 5
      end: 7
    target: PLC4
    tags:
    - tag: T3
      value: 8.0
      




